//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public string DonorName { get; set; }
        public string DonorSurname { get; set; }
        public string DonorEmail { get; set; }
        public int DonorAddress { get; set; }
        public string DonorCity { get; set; }
        public string DonorProvince { get; set; }
    }
}
