//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int OrganisationID { get; set; }
        public string OrganisationName { get; set; }
        public string OrgarnisationAddress { get; set; }
        public string OrganisationCity { get; set; }
        public string OrganisationProvince { get; set; }
    }
}
